services:
  dockerproxy:
    image: wollomatic/socket-proxy:1
    command:
      - '-loglevel=info'
      - '-allowfrom=watchtower' # allow only access from the "watchtower" service
      - '-listenip=0.0.0.0'
      - '-shutdowngracetime=10'
      # this whitelists the API endpoints that watchtower needs:
      - '-allowGET=/v1\..{2}/(containers/.*|images/.*)'
      - '-allowPOST=/v1\..{2}/(containers/.*|images/.*|networks/.*)'
      - '-allowDELETE=/v1\..{2}/(containers/.*|images/.*)'
      # check socket connection every hour and stop the proxy if it fails (will then be restarted by docker):
      - '-watchdoginterval=3600'
      - '-stoponwatchdog'
    restart: unless-stopped
    read_only: true
    mem_limit: 64M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: 65534:998 # change gid from 998 to the gid of the docker group on your host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.centurylinklabs.watchtower.enable=false # if watchtower would try to update the proxy, it would just stop
    networks:
      - docker-proxynet

  watchtower:
    image: containrrr/watchtower:1.7.1
    depends_on:
      - dockerproxy
    command:
      - '--host=tcp://dockerproxy:2375'
      - '--schedule=0 30 4 * * *'
      - '--debug'
      - '--stop-timeout=5m'
      - '--cleanup'
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    networks:
      - docker-proxynet
      - watchtower

networks:
  docker-proxynet:
    internal: true
    attachable: false
  watchtower:
    driver: bridge
    attachable: false
