name: Build and Publish

on:
  workflow_dispatch:
  # run it on push to the default repository branch
  # push:
  #   branches: [main]
  # # run it during pull request
  # pull_request:
  # schedule:
  #   - cron:  '14 3 * * 0'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set image name
      run: |
        echo "IMAGE_NAME=docker.io/wollomatic/socket-proxy" >> $GITHUB_ENV
        echo "IMAGE_VERSION=testing" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build all platforms and push to Docker hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin docker.io
        docker buildx build . --platform=linux/amd64,linux/arm64,linux/arm/v7,linux/s390x --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} --tag ${{ env.IMAGE_NAME }}:latest --push
