name: Build and Publish

on:
  workflow_dispatch:
  # run it on push to the default repository branch
  # push:
  #   branches: [main]
  # # run it during pull request
  # pull_request:
  # schedule:
  #   - cron:  '14 3 * * 0'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract tag name
        shell: bash
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
        id: get_tag

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: VERSION=${{ steps.get_tag.outputs.tag }}-${{ github.run_number }}
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/socket-proxy:${{ steps.get_tag.outputs.tag }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/socket-proxy:${{ steps.get_tag.outputs.tag }}-${{ github.run_number }}
